"""Deterministic target-specific C++ emission from a validated JSON plan."""

from __future__ import annotations

import hashlib

from protocol import PlanError


EMITTER = "grevir_irqgen_1"


def _event_type(event: dict[str, str]) -> str:
    return ("::grevir::interrupt::EventKey<"
            f'"{event["instance"]}", "{event["request"]}", "{event["kind"]}">')


def _source_type(source: str) -> str:
    return f'::grevir::interrupt::SourceKey<"{source}">'


def emit(plan: dict, application_header: str) -> tuple[bytes, bytes]:
    backend = plan["backend"]
    if backend not in ("mock", "avr", "esp32"):
        raise PlanError("interrupt emitter is not implemented for this backend")
    if any(len(group["events"]) != 1 for group in plan["source_groups"]):
        raise PlanError("this emitter needs one distinguishable event per source")
    if backend == "avr":
        if plan["target"] != "atmega328p":
            raise PlanError("unsupported AVR interrupt target")
        for binding in plan["bindings"]:
            if (binding["selector"] != "overflow" or
                    binding["configuration"] not in
                    ("normal_period", "fast_pwm8_period")):
                raise PlanError("unsupported ATmega328P Timer1 configuration")
        for group in plan["source_groups"]:
            if (group["source"], group["entry"], group["snapshot_policy"],
                    group["acknowledge_policy"]) != (
                    "timer1_ovf", "timer1_ovf_vect", "timer1_status",
                    "timer1_auto_ack"):
                raise PlanError("unsupported ATmega328P interrupt source policy")
    if backend == "esp32":
        if plan["target"] != "esp32_classic":
            raise PlanError("unsupported ESP32 interrupt target")
        for binding in plan["bindings"]:
            if (binding["selector"] != "alarm" or
                    binding["configuration"] != "period_1ms_div80"):
                raise PlanError("unsupported classic ESP32 TG0/T0 configuration")
        for group in plan["source_groups"]:
            if (group["source"], group["entry"], group["snapshot_policy"],
                    group["acknowledge_policy"]) != (
                    "tg0_t0_alarm", "tg0_t0_intr_alloc", "tg0_t0_status",
                    "tg0_t0_clear_rearm"):
                raise PlanError("unsupported classic ESP32 interrupt source policy")
    if not application_header or '"' in application_header or "\n" in application_header:
        raise PlanError("invalid application header path")
    fingerprint = plan["fingerprint"]
    header = [
        "// Generated by grevir-irqgen; edit the application declaration instead.",
        "#pragma once", "#include <grevir/interrupt/catalog.hpp>",
        "namespace grevir::interrupt {",
        "template <> struct DemandSet<::GrevirApplication> {",
        "  inline static constexpr auto value = [] {",
        f"    DemandSummary<{len(plan['demands'])}> result{{}};",
    ]
    for index, event in enumerate(plan["demands"]):
        header.append(f"    result.keys[{index}] = identity<{_event_type(event)}>();")
    header += [
        f"    result.count = {len(plan['demands'])};",
        "    return result;",
        "  }();",
        "};",
        "} // namespace grevir::interrupt",
        "namespace grevir::interrupt::detail {",
        f'inline constexpr char emission_fingerprint[] = "{fingerprint}";',
    ]
    for number, binding in enumerate(plan["bindings"], start=1):
        key = _event_type(binding["event"])
        header += [
            f"template <> struct BoundEventKey<{key}> {{",
            f"  using Event = typename EventCatalog<::GrevirApplication>::template ByKey<{key}>;",
            "  static_assert(!std::is_same_v<Event, void>, \"GREVIR_IRQ_EVENT_NOT_IN_CATALOG\");",
            f"  static constexpr unsigned id = {number}u;",
            "};",
        ]
    header += ["} // namespace grevir::interrupt::detail", ""]
    source = [
        "// Generated by grevir-irqgen; edit the application declaration instead.",
        f'#include "{application_header}"',
        "#include <grevir/interrupt/install.hpp>",
        f'static_assert(::grevir::interrupt::literal(::grevir::interrupt::detail::emission_fingerprint) == ::grevir::interrupt::literal("{fingerprint}"));',
        f'static_assert(::GrevirApplication::Board::backend == ::grevir::interrupt::literal("{backend}"));',
        f'static_assert(::GrevirApplication::Board::target == ::grevir::interrupt::literal("{plan["target"]}"));',
        f'static_assert(::GrevirApplication::Board::board == ::grevir::interrupt::literal("{plan["board"]}"));',
        f'static_assert(::GrevirApplication::Board::compiler == ::grevir::interrupt::literal("{plan["compiler"]}"));',
        f'static_assert(::grevir::interrupt::BindingPlan<::GrevirApplication>::selected.count == {len(plan["bindings"])});',
        "#if defined(__GNUC__) && !defined(__clang__)",
        "#define GREVIR_IRQ_GUARD_ATTR __attribute__((used, externally_visible))",
        "#elif defined(__clang__)",
        "#define GREVIR_IRQ_GUARD_ATTR __attribute__((used))",
        "#else",
        "#define GREVIR_IRQ_GUARD_ATTR",
        "#endif",
    ]
    if backend == "avr":
        source.append("#include <grevir/avr/devices/atmega328p/interrupt_timer1.hpp>")
    if backend == "esp32":
        source.append("#include <grevir/arduino_esp32/timer_group0_timer0.hpp>")
    for index, binding in enumerate(plan["bindings"]):
        key = _event_type(binding["event"])
        fields = [
            f"::grevir::interrupt::identity<{key}>()",
            *(f'::grevir::interrupt::literal("{binding[field]}")'
              for field in ("owner", "configuration", "source", "selector", "entry",
                            "snapshot_policy", "acknowledge_policy")),
            str(binding["dispatch_order"]),
            "true" if binding["shared_source"] else "false",
        ]
        source.append(
            f"static_assert(::grevir::interrupt::BindingPlan<::GrevirApplication>::selected.bindings[{index}] == "
            "::grevir::interrupt::BindingRecord{" + ", ".join(fields) + "});")
    for group_index, group in enumerate(plan["source_groups"]):
        guard = f"grevir_irq_source_{backend}_{group['source']}"
        source.append(f'extern "C" {{ GREVIR_IRQ_GUARD_ATTR volatile unsigned char {guard} = 0; }}')
        item = group["events"][0]
        key = _event_type(item["event"])
        call = ("  ::grevir::on_interrupt<"
                "typename ::grevir::interrupt::EventCatalog<"
                f"::GrevirApplication>::template ByKey<{key}>>();")
        if backend != "avr":
            source += [f"namespace grevir::interrupt::detail::source_{group_index} {{",
                       "void dispatch() noexcept {", call, "}", "}"]
        else:
            source += ["ISR(GREVIR_ATMEGA328P_TIMER1_OVERFLOW_VECTOR) {", call, "}"]
    source += [
        "namespace grevir::interrupt::detail {",
        "template <> bool install_bindings<::GrevirApplication>() noexcept {",
    ]
    for group_index, group in enumerate(plan["source_groups"]):
        guard = f"grevir_irq_source_{backend}_{group['source']}"
        source.append(f"  if ({guard} != 0) {{ return false; }}")
        if backend != "avr":
            source += [
                f"  if (!::GrevirApplication::Board::template install<{_source_type(group['source'])}>(",
                f"      &source_{group_index}::dispatch)) {{ return false; }}",
            ]
        else:
            source += [
                f"  if (!::GrevirApplication::Board::template install<{_source_type(group['source'])}>()) {{ return false; }}",
            ]
    source += ["  return true;", "}", "}", ""]
    return "\n".join(header).encode(), "\n".join(source).encode()


def output_identity(header: bytes, source: bytes) -> str:
    digest = hashlib.sha256()
    digest.update(header)
    digest.update(b"\0")
    digest.update(source)
    return digest.hexdigest()
